Release 3
unl/reservations pull request #102
Opened 2024-12-18 20:01 UTC by erohrs2

--Edit for later--

2024-12-19 16:49 UTC, tommyneu requested changes
Some of these changes might be better as their own issues and we can fix them later

2024-12-19 16:49 UTC, tommyneu commented on routes/checkout.rb
> +  redirect "/checkout"
This should redirect us back to the checkout with the user details pulled up

2024-12-19 16:49 UTC, tommyneu commented on views/engineering_garage/edit_teammates.erb
> +                    <td class="dcf-d-flex dcf-flex-row-rev dcf-flex-shrink-1 dcf-gap-2">
I would remove the styles from this. Looks a little wonky with it right aligned

2024-12-19 16:49 UTC, tommyneu commented on views/engineering_garage/edit_teammates.erb
> +                        <button class="dcf-btn-toggle-modal dcf-btn dcf-btn-primary" data-toggles-modal="remove-<%= teammate[:id] %>" type="button">Remove</button>
I wouldn't have this open a modal. I would replace the button/modal with just a normal form with the button being the submit button to the form. Then I would add a `onsubmit` for the "Are you sure?" thing. That is what we do for a lot of our apps and its better UX if things that look the same act the same(I think their is a law of design about that or something).

```html
<form onsubmit="return confirm('Do you really want to submit the form?');">
```

2024-12-19 16:49 UTC, tommyneu commented on views/engineering_garage/edit_project.erb
> +<h1 class="dcf-txt-h3" id="Edit_Project">Edit Project</h1>
This page needs a back button to get back to the checkout page with the user details pulled up

2024-12-19 16:49 UTC, tommyneu commented on views/engineering_garage/edit_teammates.erb
> +<h1 class="dcf-txt-h3" id="Edit_Teammates">Edit Teammates</h1>
I feel like this could get put into that edit project page. That table is basically the same except for the delete button and the user input

2024-12-19 16:49 UTC, tommyneu commented on views/engineering_garage/checkout_user.erb
> +															<div class="dcf-col-50%-end dcf-h-fixed-100% dcf-overflow-y-auto">
Remove the style `dcf-h-fixed-100%` and replace with an inline style for `max-height: 30rem;`

2025-01-16 22:46 UTC, erohrs2 commented on routes/checkout.rb
> +  redirect "/checkout"
We talked with Max about this during a meeting and he said that he wanted it to bring it back to the checkout page without user details on. If its going to be changed we should probably make it a new issue outside of this release.

2025-01-16 22:57 UTC, erohrs2 commented on views/engineering_garage/edit_teammates.erb
> +                    <td class="dcf-d-flex dcf-flex-row-rev dcf-flex-shrink-1 dcf-gap-2">
Just to make sure I understand what you are requestion, you want me to remove `class="dcf-d-flex dcf-flex-row-rev dcf-flex-shrink-1 dcf-gap-2"` from line 35 correct?

2025-01-16 23:25 UTC, erohrs2 commented on views/engineering_garage/edit_teammates.erb
> +<h1 class="dcf-txt-h3" id="Edit_Teammates">Edit Teammates</h1>
I would like this to be an issue for a different release, as it is a change to several pages and will require a bit more than a quick fix. Is this okay with you?

2025-01-16 23:32 UTC, erohrs2 commented on routes/events.rb
>  		if @user.email && !@user.email.empty?
Would you like me to get rid of the SS_ID ==8 if-else and instead only have a SS_ID == 1 check at the bottom instead? That would conform more to what you requested above but I assumed we wanted to keep innovation studio and garage code as separate as possible.

2025-01-17 00:43 UTC, erohrs2 commented on views/engineering_garage/edit_project.erb
> +<h1 class="dcf-txt-h3" id="Edit_Project">Edit Project</h1>
I went ahead and added this button to this page as well as the new project page. Let me know if you have any feedback on its placement or styling, or if you don't think the new project page should have a back button.

2025-01-17 14:17 UTC, tommyneu commented on routes/events.rb
>  		if @user.email && !@user.email.empty?
I would probably make the default the innovation studio. Then if SS_ID === 8 then do that if statement about start time.

```
template_path = innovationStudio_default
if SS_ID === 8
   if. event.start_time != nil
      template_path = engineering_normal_event
   else
      template_path = engineering_timeless_event
   end
end
```

2025-01-17 14:17 UTC, tommyneu commented on routes/checkout.rb
> +  redirect "/checkout"
We can leave it for now, but once he or the student workers start using the system they will figure out how annoying it is to keep re-scanning the person's card

2025-01-17 14:20 UTC, tommyneu commented on views/engineering_garage/edit_teammates.erb
> +                    <td class="dcf-d-flex dcf-flex-row-rev dcf-flex-shrink-1 dcf-gap-2">
Yeah remove `class="dcf-d-flex dcf-flex-row-rev dcf-flex-shrink-1 dcf-gap-2"`. All our other apps have the action buttons in a table left aligned. This will keep that design consistent

2025-01-17 14:23 UTC, tommyneu commented on views/engineering_garage/edit_project.erb
> +<h1 class="dcf-txt-h3" id="Edit_Project">Edit Project</h1>
Yeah I think having a button on both is pretty important. If a student worker clicks on the edit button, but then needs to get back to that "Check In / Check out" page it would be annoying to have to click that back button.

2025-01-17 14:24 UTC, tommyneu commented on views/engineering_garage/edit_teammates.erb
> +<h1 class="dcf-txt-h3" id="Edit_Teammates">Edit Teammates</h1>
Yeah make this it's own issue. I can send you a picture of how I made a similar thing for the chancellor email builder site

2025-01-17 14:25 UTC, tommyneu commented on views/engineering_garage/edit_project.erb
> +<h1 class="dcf-txt-h3" id="Edit_Project">Edit Project</h1>
I would probably make it a secondary button and I like making it say `< Back to Check In` or something

2025-01-17 19:26 UTC, tommyneu commented on routes/events.rb
>  		if @user.email && !@user.email.empty?
Oh ok, nevermind then. I'll resolve this conversation

2025-01-21 18:59 UTC, tommyneu approved these changes
Will make new issues to resolve some of the more minor things

2025-01-21 19:00 UTC, merged